project_id = "osglgpafsqthqolqbnwu"

[functions.market-data]
verify_jwt = false

[functions.stock-data]
verify_jwt = false

[functions.stock-fundamentals]
verify_jwt = false

[functions.stock-history]
verify_jwt = false

[functions.stock-news]
verify_jwt = false

[functions.save-daily-prices]
verify_jwt = false

[functions.import-historical-prices]
verify_jwt = false

[functions.webhook]
verify_jwt = false
